### ISSUE TITLE
[REQ] Would it possible to release the whole length.json file?

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [fengyang0317/video_reloc#1]
Some expired videos can not be download on Youtube. Thus, we are unable to obtain  frames number of all the videos via the get_frame_num.py. Would it possible to release the whole length.json file?

**Comment by fengyang0317** [comment]
The length.json file was released 11 days ago. It is under the data folder.

https://github.com/fengyang0317/video_reloc/blob/master/data/length.json
