### ISSUE TITLE
about label vector for reference video

### ISSUE THREAD

**Issue by TimmyWY2** [fengyang0317/video_reloc#4]
Hi~ 
I wonder where is the generation of the label vector for the reference video in your code?
Thanks a lot!

**Comment by fengyang0317** [comment]
https://github.com/fengyang0317/video_reloc/blob/master/create_dataset.py#L150 and https://github.com/fengyang0317/video_reloc/blob/master/input_functions.py#L31

**Comment by TimmyWY2** [comment]
thanks~
