### ISSUE TITLE
some problems about the research in this task.

### ISSUE THREAD

**Issue by hugddygff** [fengyang0317/video_reloc#5]
1. If I want to do some research, are the code and features data that you provide enough? Is there something other needed?
2. If I want to get the original video data, how to get?  use youtube-dl to download the Activitynet dataset?

**Comment by fengyang0317** [comment]
1. The code and features are enough to reproduce the results in the paper. If you want to do some research or improve the performance, I think it is a good idea to download the videos.

2. I obtain the videos from one of the coauthors. If you want to download them, you could try https://www.google.com/search?q=download+activitynet+videos&oq=download+activitynet+videos&aqs=chrome..69i57.11843j0j4&sourceid=chrome&ie=UTF-8
![image](https://user-images.githubusercontent.com/7965501/49698996-8a14ff00-fb99-11e8-942e-f2c7ed028e6a.png)

Some of the videos are no longer available on YouTube. You may ask the authors of AcitvityNet to send you the missing ones.

**Comment by hugddygff** [comment]
thanks a lot! I have started downloading the videos.
