### ISSUE TITLE
Doubt: validation/test pair(query,reference) is not fixed.

### ISSUE THREAD

**Issue by dongzhuoyao** [fengyang0317/video_reloc#7]
In you paper, you wrote:

> During our training process, the query video and reference video are randomly paired, **while the pairs are fixed for validation and testing.**

But actually in your code, the data is generated also by sampling. see below:

https://github.com/fengyang0317/video_reloc/blob/master/input_functions.py#L37

**Comment by fengyang0317** [comment]
Seed is used when validating and testing. It should generate the same random numbers.

**Comment by dongzhuoyao** [comment]
Thanks
