### ISSUE TITLE
About inside labels during training

### ISSUE THREAD

**Issue by payne53** [fengyang0317/video_reloc#8]
https://github.com/fengyang0317/video_reloc/blob/d53df139e4f89c887398107e1a0b15caee709a60/match.py#L155
Hi~. I am a little confused about the inside label. 
Do labels[:, 0] and labels[:, 1] mean start and end points?
Should it be `inside_t = tf.sequence_mask(labels[:, 0], maxlen)`
    `inside_t = tf.reverse_sequence(inside_t, labels[:, 1], 1, 0)` ?

**Comment by fengyang0317** [comment]
No. If labels is [2,5] and max_len is 8, we generate the inside label in this way.
11100000 => 00111000

**Comment by payne53** [comment]
Thank you. I thought I misunderstand the usage of `tf.reverse_sequence`.
